-- 0080_cpr_import.sql
--
-- COD SETTLEMENT IMPORT — the thing that clears Rs 13.2M of phantom debt.
--
-- WHAT THIS IS FOR
--   Finance currently shows Rs 14.8M unpaid across 6,878 parcels. Split by age,
--   Rs 13.2M of that is PostEx, older than 90 days, with ZERO OwnEx alongside
--   it. PostEx settles weekly. 3,342 parcels unpaid for over a year is not debt
--   — it is settlement that was never imported, because online_cpr has 0 rows.
--   Until a CPR lands, the receivable is fiction and the team cannot use it.
--
-- THE FOUR RULES, each learned somewhere expensive
--
--   1. GUARD FIRST, WRITE SECOND.
--      Every courier settlement sheet declares its own parcel count and total.
--      If what we parsed disagrees, the parse is wrong — and a wrong parse that
--      writes is worse than one that refuses, because it marks parcels paid
--      that were not. Nothing is written unless both match.
--
--   2. A CPR CORRECTS STATUS.
--      A courier does not pay for a parcel that came back. If a tracking number
--      is in the settlement file, it was delivered — whatever we believed. Money
--      changing hands is stronger evidence than a status poll, so the file wins
--      and every correction is reported rather than done quietly.
--
--   3. RE-UPLOADABLE, KEYED ON TRACKING NUMBER.
--      The same file dropped twice must produce the same result, not double
--      payment. Tracking ID is the key — never (store, order_number), which
--      collided on 65 parcels and would have erased the COD on 64 of them.
--
--   4. DRY RUN BY DEFAULT.
--      p_dry_run = true reports exactly what would happen and writes nothing.
--      The UI runs this first, every time.
--
-- FORMAT-AGNOSTIC ON PURPOSE
--   This function takes already-parsed rows as JSON. It does not know or care
--   whether they came from a PostEx PDF, an OwnEx XLS, or a hand-typed list.
--   Column mapping happens in the browser where a human can see the file and
--   confirm it. Guessing a courier's format cost three rounds on the OwnEx load
--   sheet; this design means it never has to be guessed at all.
--
-- Safe to run more than once.

begin;

-- ---------------------------------------------------------------------------
-- The batch record. Additive: online_cpr predates the migrations in this repo,
-- so every column is added only if missing rather than assumed.
-- ---------------------------------------------------------------------------
create table if not exists online_cpr (
  id bigint generated by default as identity primary key
);

alter table online_cpr add column if not exists cpr_number      text;
alter table online_cpr add column if not exists courier         text;
alter table online_cpr add column if not exists store_code      text;
alter table online_cpr add column if not exists cpr_date        date;
alter table online_cpr add column if not exists amount          numeric;
alter table online_cpr add column if not exists orders_count    integer;
alter table online_cpr add column if not exists status          text;
-- What the SHEET declared, kept beside what we matched. The gap between them is
-- the audit trail: a file whose parcels we could not all find is not a failure
-- to hide, it is a number to look at.
alter table online_cpr add column if not exists declared_count  integer;
alter table online_cpr add column if not exists declared_total  numeric;
alter table online_cpr add column if not exists matched_count   integer;
alter table online_cpr add column if not exists matched_total   numeric;
alter table online_cpr add column if not exists unmatched       jsonb;
alter table online_cpr add column if not exists imported_at     timestamptz default now();

create unique index if not exists online_cpr_number_courier_uidx
  on online_cpr (courier, cpr_number) where cpr_number is not null;

-- ---------------------------------------------------------------------------
-- hub_cpr_import — the whole import, guarded, in one transaction.
--
-- p_rows: [{"tracking_id":"...","net":1234.5,"fee":80,"tax":0,"paid_on":"2026-08-20"}, ...]
--         Only tracking_id is required. Everything else is optional and is left
--         untouched when absent rather than overwritten with null.
-- ---------------------------------------------------------------------------
create or replace function hub_cpr_import(
  p_courier        text,
  p_cpr_number     text,
  p_cpr_date       date,
  p_declared_count integer,
  p_declared_total numeric,
  p_rows           jsonb,
  p_dry_run        boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_parsed_count  integer;
  v_parsed_total  numeric;
  v_matched       integer;
  v_matched_total numeric;
  v_unmatched     jsonb;
  v_corrected     integer;
  v_from_status   jsonb;
  v_already_paid  integer;
  v_cpr_id        bigint;
begin
  if p_courier is null or p_cpr_number is null then
    return jsonb_build_object('ok', false, 'error', 'courier and cpr_number are required');
  end if;

  -- Land the rows in a temp table. De-duplicated on tracking_id, because a
  -- courier sheet listing the same parcel twice must not pay it twice, and
  -- Postgres rejects an upsert that hits the same conflict target twice anyway.
  create temp table _cpr (
    tracking_id text primary key,
    net numeric, fee numeric, tax numeric, paid_on date
  ) on commit drop;

  insert into _cpr (tracking_id, net, fee, tax, paid_on)
  select distinct on (btrim(r->>'tracking_id'))
         btrim(r->>'tracking_id'),
         nullif(r->>'net','')::numeric,
         nullif(r->>'fee','')::numeric,
         nullif(r->>'tax','')::numeric,
         coalesce(nullif(r->>'paid_on','')::date, p_cpr_date)
    from jsonb_array_elements(coalesce(p_rows,'[]'::jsonb)) r
   where btrim(coalesce(r->>'tracking_id','')) <> '';

  select count(*), coalesce(sum(net),0) into v_parsed_count, v_parsed_total from _cpr;

  -- ===================== THE GUARD =====================
  -- Both must agree with the sheet's own declaration or nothing is written.
  -- A 1-rupee tolerance absorbs rounding in a PDF; anything larger is a parse
  -- error wearing a rounding error's clothes.
  if p_declared_count is not null and v_parsed_count <> p_declared_count then
    return jsonb_build_object(
      'ok', false, 'guard', 'count mismatch',
      'sheet_says', p_declared_count, 'we_parsed', v_parsed_count,
      'wrote', 0,
      'meaning', 'The parse disagrees with the file''s own total. Fix the column mapping — do not import.');
  end if;

  if p_declared_total is not null and abs(v_parsed_total - p_declared_total) > 1 then
    return jsonb_build_object(
      'ok', false, 'guard', 'total mismatch',
      'sheet_says', p_declared_total, 'we_parsed', v_parsed_total,
      'difference', v_parsed_total - p_declared_total, 'wrote', 0,
      'meaning', 'The amounts parsed do not add up to the file''s declared total.');
  end if;

  -- ===================== WHAT WE CAN SEE =====================
  select count(*), coalesce(sum(c.net),0)
    into v_matched, v_matched_total
    from _cpr c join online_logistics l on l.tracking_id = c.tracking_id;

  -- Tracking numbers the courier paid for that we have no parcel for. Not an
  -- error — usually a parcel that never synced — but it must be visible.
  select coalesce(jsonb_agg(c.tracking_id), '[]'::jsonb) into v_unmatched
    from _cpr c left join online_logistics l on l.tracking_id = c.tracking_id
   where l.tracking_id is null;

  -- Rule 2: what this file is about to CORRECT. Counted before the write so it
  -- can be reported in a dry run.
  select count(*),
         coalesce(jsonb_object_agg(s, n) filter (where s is not null), '{}'::jsonb)
    into v_corrected, v_from_status
    from (select l.delivery_status as s, count(*) as n
            from _cpr c join online_logistics l on l.tracking_id = c.tracking_id
           where coalesce(l.delivery_status,'') <> 'Delivered'
           group by 1) t;

  select count(*) into v_already_paid
    from _cpr c join online_logistics l on l.tracking_id = c.tracking_id
   where coalesce(l.payment_status,'') in ('Paid','Received');

  if p_dry_run then
    return jsonb_build_object(
      'ok', true, 'dry_run', true, 'wrote', 0,
      'parsed', v_parsed_count, 'parsed_total', v_parsed_total,
      'matched', v_matched, 'matched_total', v_matched_total,
      'unmatched', jsonb_array_length(v_unmatched), 'unmatched_ids', v_unmatched,
      'would_mark_paid', v_matched,
      'already_paid', v_already_paid,
      'would_correct_to_delivered', v_corrected, 'corrected_from', v_from_status);
  end if;

  -- ===================== THE WRITE =====================
  -- coalesce on every optional field: a sheet that omits the fee must not erase
  -- a fee we already knew.
  update online_logistics l
     set payment_status = 'Paid',
         payment_date   = coalesce(c.paid_on, p_cpr_date, current_date),
         cpr_number     = p_cpr_number,
         cpr_net_amount = coalesce(c.net, l.cpr_net_amount),
         courier_fee    = coalesce(c.fee, l.courier_fee),
         courier_tax    = coalesce(c.tax, l.courier_tax),
         -- Rule 2. The courier paid, so it was delivered.
         delivery_status = 'Delivered',
         delivery_date  = coalesce(l.delivery_date, c.paid_on, p_cpr_date),
         updated_at     = now()
    from _cpr c
   where l.tracking_id = c.tracking_id;

  insert into online_cpr (cpr_number, courier, cpr_date, amount, orders_count, status,
                          declared_count, declared_total, matched_count, matched_total,
                          unmatched, imported_at)
  values (p_cpr_number, p_courier, p_cpr_date, v_matched_total, v_matched, 'Imported',
          p_declared_count, p_declared_total, v_matched, v_matched_total,
          v_unmatched, now())
  on conflict (courier, cpr_number) do update
     set cpr_date = excluded.cpr_date, amount = excluded.amount,
         orders_count = excluded.orders_count, declared_count = excluded.declared_count,
         declared_total = excluded.declared_total, matched_count = excluded.matched_count,
         matched_total = excluded.matched_total, unmatched = excluded.unmatched,
         imported_at = now()
  returning id into v_cpr_id;

  return jsonb_build_object(
    'ok', true, 'dry_run', false, 'cpr_id', v_cpr_id,
    'parsed', v_parsed_count, 'matched', v_matched, 'matched_total', v_matched_total,
    'marked_paid', v_matched,
    'corrected_to_delivered', v_corrected, 'corrected_from', v_from_status,
    'unmatched', jsonb_array_length(v_unmatched), 'unmatched_ids', v_unmatched,
    'report', v_matched || ' paid · ' || v_corrected || ' corrected to Delivered · ' ||
              jsonb_array_length(v_unmatched) || ' not found');
end;
$function$;

grant execute on function hub_cpr_import(text, text, date, integer, numeric, jsonb, boolean) to authenticated;

commit;

-- ===========================================================================
-- USE — always dry run first. The UI does this automatically.
-- ===========================================================================
-- select hub_cpr_import(
--   'PostEx', 'CPR-2026-08-001', '2026-08-20',
--   2,            -- parcel count the SHEET declares
--   4196.00,      -- total the SHEET declares
--   '[{"tracking_id":"28205020006233","net":3397,"fee":80},
--     {"tracking_id":"26205020006647","net":799,"fee":80}]'::jsonb,
--   true);        -- dry run
--
-- Then the same call with false to write.
--
-- -- Undo one batch if a mapping turns out wrong (status is NOT restored —
-- -- the next courier poll does that):
-- -- update online_logistics set payment_status = null, payment_date = null,
-- --        cpr_number = null, cpr_net_amount = null
-- --  where cpr_number = 'CPR-2026-08-001';
