-- 0084_unpay_returns.sql
--
-- 588 PARCELS SAY "Returned" AND "Paid" AT THE SAME TIME.
--
-- A COD parcel that came back collected no cash, so the courier paid nothing
-- for it. Both facts cannot be true.
--
-- WHICH ONE IS THE LIE — settled by evidence, not by reasoning
--   Two possibilities existed, needing opposite repairs:
--     A. the PAYMENT is wrong  -> clear it
--     B. the STATUS is wrong (delivered, then a sync flipped it — the 0059
--        return-leg bug did exactly this) -> keep the payment, fix the status
--
--   Three things decide it:
--
--   1. The courier's own 93 receipts were imported first. Anything PostEx
--      really delivered was corrected to Delivered by that import and left this
--      population on its own. 593 became 588 — so five were case (B), and they
--      are already fixed. The rest are not in any receipt as delivered.
--
--   2. Their recorded net is NEGATIVE: −171,202 across the group, roughly −288
--      each, which is precisely shipping + GST. That is the shape of a CHARGE.
--      A delivered parcel's net is positive.
--
--   3. online_cpr was empty when these were written. They were marked paid
--      under hand-typed labels — 'PostEx-Aug19', 'Manual-Jul31' — that PostEx
--      has never heard of and nothing can be reconciled against.
--
--   So: case (A). The money is already recorded correctly as a charge. The word
--   "Paid" on top of it is the only thing wrong, and it is counting Rs 1.35M of
--   COD as revenue that was never collected.
--
-- WHAT IS AND IS NOT TOUCHED
--   cleared : payment_status, payment_date          — the false claim
--   kept    : courier_fee, courier_tax, cpr_number  — the charge is real money
--             and belongs on the parcel
--   kept    : delivery_status                       — Returned is correct
--
-- THE SAFETY RULE
--   Only rows whose recorded net is <= 0 are touched. A positive net would mean
--   a real payment was recorded, and that contradicts the evidence above — such
--   a row is left alone and reported for a human to look at. This migration
--   corrects what is provable and refuses to guess at the rest.
--
-- REVERSIBLE. Every old value is copied to online_payment_corrections first.
-- This moves money on a page people make decisions from; it should be possible
-- to put back.
--
-- Safe to run more than once — the second run finds nothing left to correct.

begin;

create table if not exists online_payment_corrections (
  id              bigint generated by default as identity primary key,
  tracking_id     text not null,
  courier         text,
  delivery_status text,
  old_payment_status text,
  old_payment_date   date,
  old_cpr_number     text,
  cod_amount      numeric,
  cpr_net_amount  numeric,
  reason          text,
  corrected_at    timestamptz default now()
);

comment on table online_payment_corrections is
  'Every payment flag cleared by a correction migration, with its old values. Undo is a single insert-back from here.';

-- ---------------------------------------------------------------------------
-- 1. Record what is about to change.
-- ---------------------------------------------------------------------------
insert into online_payment_corrections (
    tracking_id, courier, delivery_status, old_payment_status, old_payment_date,
    old_cpr_number, cod_amount, cpr_net_amount, reason)
select l.tracking_id, l.courier, l.delivery_status, l.payment_status, l.payment_date,
       l.cpr_number, l.cod_amount, l.cpr_net_amount,
       '0084: returned parcel marked paid; recorded net is a charge, not a payment'
  from online_logistics l
 where l.delivery_status in ('Returned', 'RTS')
   and coalesce(l.payment_status, '') in ('Paid', 'Received')
   and coalesce(l.cpr_net_amount, 0) <= 0
   -- do not record the same correction twice on a re-run
   and not exists (
     select 1 from online_payment_corrections c
      where c.tracking_id = l.tracking_id and c.reason like '0084:%');

-- ---------------------------------------------------------------------------
-- 2. Clear the false claim. Nothing else.
-- ---------------------------------------------------------------------------
update online_logistics
   set payment_status = null,
       payment_date   = null,
       updated_at     = now()
 where delivery_status in ('Returned', 'RTS')
   and coalesce(payment_status, '') in ('Paid', 'Received')
   and coalesce(cpr_net_amount, 0) <= 0;

commit;

-- ===========================================================================
-- VERIFY
-- ===========================================================================
-- -- 1. How many were corrected, and what they were worth.
-- select count(*) as corrected,
--        to_char(sum(cod_amount), 'FM999,999,999')     as cod_no_longer_counted_as_revenue,
--        to_char(sum(cpr_net_amount), 'FM999,999,999') as charge_kept_on_the_parcel
--   from online_payment_corrections where reason like '0084:%';
--
-- -- 2. What is LEFT contradictory. These have a POSITIVE net, so the evidence
-- --    points the other way and they were deliberately not touched. If this is
-- --    above zero, look at them by hand before doing anything else.
-- select tracking_id, courier, delivery_status, payment_status,
--        cod_amount, cpr_net_amount, cpr_number
--   from online_logistics
--  where delivery_status in ('Returned','RTS')
--    and coalesce(payment_status,'') in ('Paid','Received')
--  order by cpr_net_amount desc
--  limit 20;
--
-- -- 3. The money, before and after. received_gross should FALL by roughly the
-- --    figure in (1); pending should not move, because a returned parcel is not
-- --    a receivable and drops out of v_finance_payments entirely.
-- select * from hub_finance_by_courier(null, null, 'ALL');
--
-- ===========================================================================
-- UNDO, if any of this turns out wrong
-- ===========================================================================
-- update online_logistics l
--    set payment_status = c.old_payment_status,
--        payment_date   = c.old_payment_date
--   from online_payment_corrections c
--  where c.tracking_id = l.tracking_id and c.reason like '0084:%';
-- ===========================================================================
