-- 0085_close_aged_returns.sql
--
-- CLOSE THE RETURN BACKLOG OLDER THAN FOUR MONTHS.
--
-- THE ONGOING RULE IS ALREADY CORRECT — this does not change it.
--   v_returns_all has said this since 0073:
--
--       needs_chasing = (return_received_at is null AND cancelled_at is null)
--
--   which is exactly the rule Zeeshan described: a return keeps chasing until
--   the box is physically in hand, OR the agent cancels the order in Shopify.
--   The agent's cancellation IS the receipt confirmation — there is no separate
--   step for the warehouse to perform and no screen to build.
--
--   The money side is already right too. A returned parcel only appears in
--   v_finance_payments if it has been paid, so it is never counted as a
--   receivable. It stays pending, as it should.
--
-- SO WHAT IS ACTUALLY WRONG
--   Only the backlog. 249 returns are still marked pending, the oldest 229 days
--   old, from before that rule existed. Nobody is going to chase a claim from
--   January — couriers stop honouring them long before that — and leaving them
--   in the list buries the ones that can still be recovered.
--
-- THE CUTOFF
--   Four months, as agreed: anything whose return date is before 27 Apr 2026 is
--   closed. Change p_cutoff below if you want a different line; nothing else
--   depends on the exact date.
--
-- CLOSED IS NOT THE SAME AS RECEIVED, AND IS NOT RECORDED AS IF IT WERE.
--   Setting return_received_at is the only mechanism that removes a row from
--   the chase list, so it has to be set — but writing that alone would claim a
--   box was received when nobody knows whether it was. return_closed_reason
--   records WHY it left the list, so a genuine receipt and an aged write-off
--   are never confused for one another afterwards.
--
-- REVERSIBLE. Old values are copied out first; the undo is at the bottom.
-- Safe to run more than once.

begin;

alter table online_logistics
  add column if not exists return_closed_reason text;

comment on column online_logistics.return_closed_reason is
  'Why a return stopped being chased, when it was not an actual physical receipt. Null means return_received_at is a real receipt. Set by 0085 for the aged backlog.';

create table if not exists online_return_closures (
  id                 bigint generated by default as identity primary key,
  tracking_id        text not null,
  courier            text,
  order_number       text,
  store_code         text,
  delivery_status    text,
  return_date        date,
  age_days           integer,
  cod_amount         numeric,
  old_return_received_at timestamptz,
  reason             text,
  closed_at          timestamptz default now()
);

comment on table online_return_closures is
  'Returns closed in bulk rather than physically received, with their prior state. Undo is a single update from here.';

do $do$
declare
  -- Four months back from the day this was agreed (27 Aug 2026).
  p_cutoff date := date '2026-04-27';
  v_closed integer;
begin

  insert into online_return_closures (
      tracking_id, courier, order_number, store_code, delivery_status,
      return_date, age_days, cod_amount, old_return_received_at, reason)
  select l.tracking_id, l.courier, l.order_number, l.store_code, l.delivery_status,
         coalesce(l.return_leg_started_at::date, l.delivery_date, l.dispatch_date),
         current_date - coalesce(l.return_leg_started_at::date, l.delivery_date, l.dispatch_date),
         l.cod_amount, l.return_received_at,
         '0085: return older than ' || p_cutoff || ', closed as no longer chaseable'
    from online_logistics l
   where l.delivery_status in ('Returned', 'RTS')
     and l.return_received_at is null
     and coalesce(l.return_leg_started_at::date, l.delivery_date, l.dispatch_date) < p_cutoff
     and not exists (
       select 1 from online_return_closures c
        where c.tracking_id = l.tracking_id and c.reason like '0085:%');

  update online_logistics l
     set return_received_at   = now(),
         return_closed_reason = 'aged: closed in bulk, not physically confirmed',
         updated_at           = now()
   where l.delivery_status in ('Returned', 'RTS')
     and l.return_received_at is null
     and coalesce(l.return_leg_started_at::date, l.delivery_date, l.dispatch_date) < p_cutoff;

  get diagnostics v_closed = row_count;
  raise notice '0085: closed % aged returns (cutoff %)', v_closed, p_cutoff;
end
$do$;

commit;

-- ===========================================================================
-- VERIFY
-- ===========================================================================
-- -- 1. What was closed, and what it was worth. These are NOT losses — the COD
-- --    was never collected on a return. It is the size of the backlog removed.
-- select count(*) as closed,
--        to_char(sum(cod_amount), 'FM999,999,999') as cod_on_those_parcels,
--        min(return_date) as oldest, max(return_date) as newest
--   from online_return_closures where reason like '0085:%';
--
-- -- 2. What is LEFT to chase. Should be only the last four months, and the
-- --    oldest should now be under ~120 days.
-- select count(*) as still_chasing,
--        max(age_days) as oldest_days,
--        to_char(sum(cod_amount), 'FM999,999,999') as cod
--   from v_returns_all where needs_chasing;
--
-- -- 3. Genuine receipts are still distinguishable from bulk closures:
-- select coalesce(return_closed_reason, 'physically received') as how, count(*)
--   from online_logistics
--  where return_received_at is not null
--  group by 1;
--
-- ===========================================================================
-- UNDO
-- ===========================================================================
-- update online_logistics l
--    set return_received_at   = c.old_return_received_at,
--        return_closed_reason = null
--   from online_return_closures c
--  where c.tracking_id = l.tracking_id and c.reason like '0085:%';
-- ===========================================================================
