-- 0118_retail_schema_completion.sql
--
-- FS TRADERS: the ten tables and three columns the retail port never got.
--
-- WHAT IS THERE NOW
--   Fifteen retail_* tables exist and are empty. They were created outside this
--   migration series — nothing in supabase/migrations/ declares them — so this
--   file re-declares them defensively (create table if not exists) and then adds
--   what is missing. Running it against the live database changes nothing that
--   already exists.
--
-- WHY THE MISSING PIECES MATTER
--   retail_expenses and retail_employee_ledger have no dedupe_key. That single
--   omission makes the Nimbus import impossible to write safely: the old system
--   doubled every Head Office expense on save (19,770 -> 39,540 -> 59,310 ->
--   79,080) precisely because the delete-then-insert had nothing unique to land
--   on. The partial unique index below is what stops it happening again, and it
--   is a database guarantee, not a UI check.
--
--   Everything else here is a table a whole module needs: no bank_accounts means
--   no bank statements, no card_slip_files means card reconciliation cannot
--   deduplicate an uploaded screenshot, no upload_log means nobody is told a
--   day was never uploaded.
--
-- Safe to run more than once.

begin;

-- ===========================================================================
-- 1. Expense categories — the dropdown behind every manual expense.
-- ===========================================================================
create table if not exists retail_expense_categories (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  active     boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

insert into retail_expense_categories (name, sort_order) values
  ('Shop Expense', 10), ('Utilities', 20), ('Rent', 30), ('Salary', 40),
  ('Advance', 50), ('Tea & Food', 60), ('Transport', 70), ('Repair', 80),
  ('Packing', 90), ('Marketing', 100), ('Misc', 999)
on conflict (name) do nothing;

-- ===========================================================================
-- 2. Bank accounts — Alfalah, Meezan, JazzCash. Owner-tier data.
-- ===========================================================================
create table if not exists retail_bank_accounts (
  id              bigint generated by default as identity primary key,
  bank            text not null,
  label           text not null,
  account_no      text,
  opening_balance numeric not null default 0,
  opening_date    date,
  active          boolean not null default true,
  sort            integer not null default 0,
  branch_id       bigint references retail_branches(id) on delete set null,
  created_at      timestamptz not null default now()
);

-- ===========================================================================
-- 3. Statement files — one row per uploaded PDF/image, hashed.
--    The hash is what makes re-uploading the same statement a no-op.
-- ===========================================================================
create table if not exists retail_stmt_files (
  id          bigint generated by default as identity primary key,
  file_hash   text not null unique,
  file_name   text,
  account_id  bigint references retail_bank_accounts(id) on delete set null,
  n_rows      integer not null default 0,
  from_date   date,
  to_date     date,
  uploaded_at timestamptz not null default now()
);

-- ===========================================================================
-- 4. Bank transactions — every line of every statement.
--
--    (account_id, dedupe_key) is UNIQUE. That is the whole reason a statement
--    can be uploaded twice without duplicating a payment. Do not relax it to a
--    plain index because an import "felt slow".
-- ===========================================================================
create table if not exists retail_bank_txns (
  id           bigint generated by default as identity primary key,
  account_id   bigint not null references retail_bank_accounts(id) on delete cascade,
  txn_date     date not null,
  txn_time     text,
  direction    text not null check (direction in ('credit','debit')),
  amount       numeric not null,
  balance      numeric,
  descr        text,
  ref_no       text,
  ref          text,
  branch_id    bigint references retail_branches(id) on delete set null,
  category     text,
  counterparty text,
  suggest      text,
  auto         boolean not null default false,
  needs_ref    boolean not null default true,
  file_id      bigint references retail_stmt_files(id) on delete set null,
  dedupe_key   text not null,
  source       text not null default 'statement',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create unique index if not exists retail_bank_txns_dedupe_idx on retail_bank_txns (account_id, dedupe_key);
create index if not exists retail_bank_txns_date_idx  on retail_bank_txns (txn_date);
create index if not exists retail_bank_txns_needs_idx on retail_bank_txns (needs_ref) where needs_ref;

-- ===========================================================================
-- 5. Reference rules — the learned narration -> reference/branch mappings
--    that auto-name a recurring transaction the second time it appears.
-- ===========================================================================
create table if not exists retail_ref_rules (
  id         bigint generated by default as identity primary key,
  bank       text,
  direction  text,
  match_type text not null default 'contains',
  pattern    text not null,
  ref        text not null,
  branch_id  bigint references retail_branches(id) on delete set null,
  account_id bigint references retail_bank_accounts(id) on delete cascade,
  category   text,
  priority   integer not null default 100,
  hits       integer not null default 0,
  active     boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists retail_ref_rules_active_idx on retail_ref_rules (active, priority);

-- ===========================================================================
-- 6/7. Card reconciliation.
--
--   Card money from all nine shops lands mixed in one pooled Alfalah account
--   with no shop name attached, so a settlement is matched to a branch by
--   nearest expected value. Two unique indexes stop the same credit being
--   counted twice: one on the bank's own transaction id, one on the
--   (date, amount, ref) triple for rows that arrive without one.
-- ===========================================================================
create table if not exists retail_card_slip_files (
  id          bigint generated by default as identity primary key,
  file_hash   text not null unique,
  file_name   text,
  branch_id   bigint references retail_branches(id) on delete set null,
  n_rows      integer not null default 0,
  uploaded_at timestamptz not null default now()
);

create table if not exists retail_card_settlements (
  id          bigint generated by default as identity primary key,
  file_id     bigint references retail_card_slip_files(id) on delete cascade,
  branch_id   bigint references retail_branches(id) on delete set null,
  credit_date date not null,
  credit_time text,
  sale_date   date,
  amount      numeric(14,2) not null,
  ref         text not null default '',
  bank        text,
  descr       text,
  source      text not null default 'screenshot',
  created_at  timestamptz not null default now()
);
create index        if not exists retail_card_settlements_branch_date_idx on retail_card_settlements (branch_id, credit_date);
create index        if not exists retail_card_settlements_date_idx        on retail_card_settlements (credit_date);
create unique index if not exists retail_card_settlements_dedupe_uq       on retail_card_settlements (credit_date, amount, ref);
create unique index if not exists retail_card_settlements_txid_uq         on retail_card_settlements (ref) where ref <> '';

-- ===========================================================================
-- 8. Import batches — one row per Nimbus upload, for the audit trail.
-- ===========================================================================
create table if not exists retail_import_batches (
  id             bigint generated by default as identity primary key,
  filename       text,
  row_count      integer not null default 0,
  inserted_count integer not null default 0,
  skipped_count  integer not null default 0,
  total_sales    numeric not null default 0,
  imported_by    text,
  note           text,
  imported_at    timestamptz not null default now()
);

-- ===========================================================================
-- 9. Upload log — records that a given unit/date/kind HAS been uploaded, so
--    the app can say which shop-days are still missing. Absence is the signal.
-- ===========================================================================
create table if not exists retail_upload_log (
  id          bigint generated by default as identity primary key,
  unit        text not null,
  log_date    date not null,
  kind        text not null,
  uploaded_at timestamptz not null default now(),
  unique (unit, log_date, kind)
);

-- ===========================================================================
-- 10. Attendance — shop floor and head office, one row per person per day.
-- ===========================================================================
create table if not exists retail_attendance (
  id          bigint generated by default as identity primary key,
  employee_id bigint not null references retail_employees(id) on delete cascade,
  att_date    date not null,
  status      text default 'present' check (status in ('present','absent','half','leave','off')),
  time_in     text,
  time_out    text,
  note        text,
  created_at  timestamptz not null default now(),
  unique (employee_id, att_date)
);
create index if not exists retail_attendance_emp_date on retail_attendance (employee_id, att_date);

-- ===========================================================================
-- 11. The three missing columns on tables that already exist.
-- ===========================================================================

-- credit_sale: FC udhaar. It is NOT a credit card, and it never enters the
-- till, so it is carried beside cash rather than inside the closing sum.
alter table retail_daily_book add column if not exists credit_sale numeric default 0;

-- dedupe_key: the idempotency key for the Nimbus import. A PARTIAL unique index
-- (source = 'nimbus') is used rather than a plain one because manual rows are
-- allowed to repeat — two identical Rs 500 tea expenses typed on the same day
-- are two real expenses, not a duplicate.
alter table retail_expenses        add column if not exists dedupe_key text;
alter table retail_employee_ledger add column if not exists dedupe_key text;

create unique index if not exists retail_expenses_nimbus_dedupe
  on retail_expenses (dedupe_key) where source = 'nimbus';
create unique index if not exists retail_employee_ledger_nimbus_dedupe
  on retail_employee_ledger (dedupe_key) where source = 'nimbus';

-- The import batch a sale line came from, now that batches exist.
do $do$
begin
  if not exists (select 1 from pg_constraint where conname = 'retail_sale_lines_batch_fk') then
    alter table retail_sale_lines
      add constraint retail_sale_lines_batch_fk
      foreign key (import_batch_id) references retail_import_batches(id) on delete set null;
  end if;
end $do$;

-- ===========================================================================
-- 12. The check constraints the port dropped. Each one encodes a rule that
--     already went wrong once.
-- ===========================================================================
do $do$
begin
  -- 'credit' is udhaar. Card is 'meezan_card' and nothing else. Counting
  -- Nimbus MOP "Credit" as card is what made FC DHA's 1 Sep card figure read
  -- 36,100 instead of 33,400.
  if not exists (select 1 from pg_constraint where conname = 'retail_sale_lines_payment_method_check') then
    alter table retail_sale_lines add constraint retail_sale_lines_payment_method_check
      check (payment_method in ('cash','jazzcash','meezan_card','online','other','credit','unclassified'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retail_expenses_paid_via_check') then
    alter table retail_expenses add constraint retail_expenses_paid_via_check
      check (paid_via in ('cash','jazzcash','meezan_card','bank','other'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retail_expenses_txn_type_check') then
    alter table retail_expenses add constraint retail_expenses_txn_type_check
      check (txn_type in ('expense','income'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retail_expenses_source_check') then
    alter table retail_expenses add constraint retail_expenses_source_check
      check (source in ('manual','nimbus'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retail_ho_cashflow_direction_check') then
    alter table retail_ho_cashflow add constraint retail_ho_cashflow_direction_check
      check (direction in ('in','out'));
  end if;
end $do$;

commit;

-- ===========================================================================
-- VERIFY
-- ===========================================================================
-- -- All 25 retail tables should be listed.
-- select table_name from information_schema.tables
--  where table_schema='public' and table_name like 'retail%' order by 1;
--
-- -- The three columns that were missing.
-- select table_name, column_name from information_schema.columns
--  where table_schema='public'
--    and (table_name='retail_daily_book'       and column_name='credit_sale')
--     or (table_name='retail_expenses'         and column_name='dedupe_key')
--     or (table_name='retail_employee_ledger'  and column_name='dedupe_key');
--
-- -- The two partial unique indexes that make the import idempotent.
-- select indexname from pg_indexes
--  where schemaname='public' and indexname like '%nimbus_dedupe';
-- ===========================================================================
